-- =====================================================================
-- Controla Gastos — schema do Supabase
--
-- Cole este arquivo inteiro no SQL Editor do Supabase e execute uma vez.
-- Pode ser executado de novo sem problema: tudo é idempotente.
--
-- Como o navegador fala direto com o banco, as regras de negócio ficam
-- AQUI, e não no JavaScript: o que está no navegador qualquer pessoa
-- consegue contornar, o que está no banco não.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Tabelas
-- ---------------------------------------------------------------------

create table if not exists public.pastas (
    id        bigint generated by default as identity primary key,
    user_id   uuid   not null default auth.uid() references auth.users (id) on delete cascade,
    nome      text   not null check (length(btrim(nome)) between 1 and 120),
    subtitulo text   not null default '' check (length(subtitulo) <= 160),
    icone     text   not null default 'folder' check (length(icone) <= 40),
    cor       text   not null default '#3b82f6' check (cor ~ '^#[0-9a-fA-F]{6}$'),
    ordem     int    not null default 99,
    criado_em timestamptz not null default now(),
    unique (user_id, nome)
);

create table if not exists public.contas (
    id       bigint generated by default as identity primary key,
    user_id  uuid   not null default auth.uid() references auth.users (id) on delete cascade,
    pasta_id bigint not null references public.pastas (id) on delete cascade,
    codigo   text   not null default '' check (length(codigo) <= 20),
    nome     text   not null check (length(btrim(nome)) between 1 and 120),
    tipo     text   not null check (tipo in ('receita', 'despesa')),
    cor      text   not null default '#3b82f6' check (cor ~ '^#[0-9a-fA-F]{6}$'),
    ativo    boolean not null default true,
    criado_em timestamptz not null default now(),
    unique (pasta_id, tipo, nome)
);

create table if not exists public.lancamentos (
    id             bigint generated by default as identity primary key,
    user_id        uuid   not null default auth.uid() references auth.users (id) on delete cascade,
    -- pasta_id e tipo são preenchidos pelo gatilho a partir da conta:
    -- é o que impede lançar uma despesa como receita ou na pasta errada.
    pasta_id       bigint not null references public.pastas (id) on delete restrict,
    conta_id       bigint not null references public.contas (id) on delete restrict,
    tipo           text   not null check (tipo in ('receita', 'despesa')),
    data           date   not null default current_date,
    descricao      text   not null default '' check (length(descricao) <= 160),
    valor_centavos bigint not null check (valor_centavos > 0 and valor_centavos <= 10000000000000),
    observacao     text   not null default '' check (length(observacao) <= 500),
    criado_em      timestamptz not null default now()
);

create index if not exists idx_pastas_user  on public.pastas (user_id, ordem, nome);
create index if not exists idx_contas_user  on public.contas (user_id, pasta_id, tipo);
create index if not exists idx_lanc_user    on public.lancamentos (user_id, data desc);
create index if not exists idx_lanc_conta   on public.lancamentos (conta_id);
create index if not exists idx_lanc_pasta   on public.lancamentos (pasta_id, data);

-- ---------------------------------------------------------------------
-- Regras de negócio (gatilhos)
-- ---------------------------------------------------------------------

-- O tipo e a pasta do lançamento vêm sempre da conta escolhida. O que o
-- navegador mandar nesses dois campos é ignorado.
create or replace function public.lancamento_derivar_da_conta()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
    conta public.contas%rowtype;
begin
    select * into conta from public.contas where id = new.conta_id;

    if not found then
        raise exception 'Conta do plano de contas não encontrada.' using errcode = 'P0002';
    end if;
    if conta.user_id <> new.user_id then
        raise exception 'Esta conta pertence a outro usuário.' using errcode = 'P0001';
    end if;
    if not conta.ativo then
        raise exception 'A conta "%" está inativa.', conta.nome using errcode = 'P0001';
    end if;

    new.tipo := conta.tipo;
    new.pasta_id := conta.pasta_id;
    return new;
end;
$$;

drop trigger if exists trg_lancamento_derivar on public.lancamentos;
create trigger trg_lancamento_derivar
    before insert or update on public.lancamentos
    for each row execute function public.lancamento_derivar_da_conta();

-- Uma conta que já tem lançamentos não pode mudar de tipo: isso viraria
-- receita virando despesa no histórico inteiro.
create or replace function public.conta_proteger_tipo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.tipo <> old.tipo
       and exists (select 1 from public.lancamentos where conta_id = old.id) then
        raise exception 'Não é possível mudar o tipo de uma conta que já possui lançamentos.'
            using errcode = 'P0001';
    end if;
    return new;
end;
$$;

drop trigger if exists trg_conta_proteger_tipo on public.contas;
create trigger trg_conta_proteger_tipo
    before update on public.contas
    for each row execute function public.conta_proteger_tipo();

-- Se a conta muda de pasta, os lançamentos dela acompanham.
create or replace function public.conta_propagar_pasta()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if new.pasta_id <> old.pasta_id then
        update public.lancamentos set pasta_id = new.pasta_id where conta_id = new.id;
    end if;
    return null;
end;
$$;

drop trigger if exists trg_conta_propagar_pasta on public.contas;
create trigger trg_conta_propagar_pasta
    after update on public.contas
    for each row execute function public.conta_propagar_pasta();

-- ---------------------------------------------------------------------
-- Segurança: cada pessoa só enxerga os próprios dados
-- ---------------------------------------------------------------------

alter table public.pastas      enable row level security;
alter table public.contas      enable row level security;
alter table public.lancamentos enable row level security;

do $$
declare
    tabela text;
begin
    foreach tabela in array array['pastas', 'contas', 'lancamentos'] loop
        execute format('drop policy if exists %I on public.%I', tabela || '_proprios', tabela);
        execute format(
            'create policy %I on public.%I for all to authenticated
                 using (user_id = auth.uid()) with check (user_id = auth.uid())',
            tabela || '_proprios', tabela);
    end loop;
end;
$$;

-- Visitante não autenticado não tem acesso a nada.
revoke all on public.pastas, public.contas, public.lancamentos from anon;
grant select, insert, update, delete
    on public.pastas, public.contas, public.lancamentos to authenticated;

-- ---------------------------------------------------------------------
-- Dados iniciais de cada usuário novo
-- ---------------------------------------------------------------------

create or replace function public.preparar_conta_nova()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    dono uuid := auth.uid();
    id_corretor bigint;
    id_barbearia bigint;
    id_casa bigint;
begin
    if dono is null then
        raise exception 'É preciso estar autenticado.' using errcode = 'P0001';
    end if;
    -- Já tem dados: não faz nada (a função pode ser chamada a cada login).
    if exists (select 1 from public.pastas where user_id = dono) then
        return;
    end if;

    insert into public.pastas (user_id, nome, subtitulo, icone, cor, ordem)
         values (dono, 'Corretor', 'Comissões • Despesas • Lucro', 'corretor', '#f5a524', 1)
      returning id into id_corretor;
    insert into public.pastas (user_id, nome, subtitulo, icone, cor, ordem)
         values (dono, 'Barbearia', 'Vendas • Despesas • Lucro', 'barbearia', '#3b82f6', 2)
      returning id into id_barbearia;
    insert into public.pastas (user_id, nome, subtitulo, icone, cor, ordem)
         values (dono, 'Casa', 'Moradia • Contas • Despesas', 'casa', '#22c55e', 3)
      returning id into id_casa;

    insert into public.contas (user_id, pasta_id, codigo, nome, tipo, cor) values
        (dono, id_corretor,  '1.01', 'Comissão de venda',            'receita', '#22c55e'),
        (dono, id_corretor,  '1.02', 'Comissão de locação',          'receita', '#16a34a'),
        (dono, id_corretor,  '1.99', 'Outras receitas',              'receita', '#4ade80'),
        (dono, id_corretor,  '2.01', 'Combustível',                  'despesa', '#3b82f6'),
        (dono, id_corretor,  '2.02', 'Marketing',                    'despesa', '#f97316'),
        (dono, id_corretor,  '2.03', 'Alimentação',                  'despesa', '#22c55e'),
        (dono, id_corretor,  '2.04', 'Internet/Telefone',            'despesa', '#8b5cf6'),
        (dono, id_corretor,  '2.99', 'Outros',                       'despesa', '#94a3b8'),
        (dono, id_barbearia, '1.01', 'Serviços (cortes e barba)',    'receita', '#22c55e'),
        (dono, id_barbearia, '1.02', 'Venda de produtos',            'receita', '#16a34a'),
        (dono, id_barbearia, '1.99', 'Outras receitas',              'receita', '#4ade80'),
        (dono, id_barbearia, '2.01', 'Produtos (pomadas, etc.)',     'despesa', '#3b82f6'),
        (dono, id_barbearia, '2.02', 'Aluguel',                      'despesa', '#f97316'),
        (dono, id_barbearia, '2.03', 'Energia/Água',                 'despesa', '#22c55e'),
        (dono, id_barbearia, '2.04', 'Internet/Telefone',            'despesa', '#8b5cf6'),
        (dono, id_barbearia, '2.99', 'Outros',                       'despesa', '#94a3b8'),
        (dono, id_casa,      '1.01', 'Salário',                      'receita', '#22c55e'),
        (dono, id_casa,      '1.02', 'Bônus/Extras',                 'receita', '#16a34a'),
        (dono, id_casa,      '1.99', 'Outras receitas',              'receita', '#4ade80'),
        (dono, id_casa,      '2.01', 'Moradia (aluguel/cond.)',      'despesa', '#3b82f6'),
        (dono, id_casa,      '2.02', 'Contas (água, luz, internet)', 'despesa', '#f97316'),
        (dono, id_casa,      '2.03', 'Alimentação',                  'despesa', '#22c55e'),
        (dono, id_casa,      '2.04', 'Transporte',                   'despesa', '#8b5cf6'),
        (dono, id_casa,      '2.99', 'Outros',                       'despesa', '#ec4899');
end;
$$;

revoke all on function public.preparar_conta_nova() from public, anon;
grant execute on function public.preparar_conta_nova() to authenticated;
