/**
 * Conexão com o banco (PostgreSQL / Neon) e criação do schema.
 *
 * O driver é o "pg", que é JavaScript puro — sem binário nativo, que foi
 * justamente o que quebrava a função serverless antes. Ele conversa tanto com o
 * Neon (usando a DATABASE_URL que a Vercel injeta) quanto com um PostgreSQL
 * comum na sua máquina, então o código é o mesmo nos dois casos.
 */

import pg from "pg";

import { ErroApi } from "./_erros.js";

export type ModoArmazenamento = "neon" | "local" | "sem-banco";

// Sem isto, o driver devolve BIGINT (SUM, COUNT) como string, e as somas do
// painel virariam concatenação de texto em vez de aritmética.
pg.types.setTypeParser(pg.types.builtins.INT8, (valor) => Number(valor));

const NA_VERCEL = Boolean(process.env.VERCEL);

/**
 * A integração do Neon pelo Marketplace da Vercel cadastra a variável sozinha.
 * Aceitamos os nomes usuais para não depender de um só.
 */
const NOMES_URL = ["DATABASE_URL", "POSTGRES_URL", "PGURL", "DATABASE_URL_UNPOOLED"];

function urlDoBanco(): string | undefined {
  for (const nome of NOMES_URL) {
    const valor = process.env[nome]?.trim();
    if (valor && /^postgres(ql)?:\/\//.test(valor)) return valor;
  }
  return undefined;
}

export function modoArmazenamento(): ModoArmazenamento {
  const url = urlDoBanco();
  if (!url) return "sem-banco";
  return /localhost|127\.0\.0\.1/.test(url) ? "local" : "neon";
}

export const SEM_BANCO =
  "Este site ainda não tem um banco de dados conectado. Na Vercel, abra a aba Storage " +
  "do projeto, conecte o banco Neon a este projeto e clique em Redeploy.";

/** O Neon exige TLS; um PostgreSQL local normalmente não tem certificado. */
export function configuracaoSsl(url: string): pg.ConnectionConfig["ssl"] {
  if (/sslmode=disable/.test(url)) return false;
  if (/@(localhost|127\.0\.0\.1)[:/]/.test(url)) return false;
  return { rejectUnauthorized: true };
}

let pool: pg.Pool | undefined;

function conexoes(): pg.Pool {
  if (!pool) {
    const url = urlDoBanco();
    if (!url) throw new ErroApi(SEM_BANCO, 503);
    pool = new pg.Pool({
      connectionString: url,
      ssl: configuracaoSsl(url),
      // Cada instância serverless atende uma requisição por vez; abrir mais
      // conexões só desperdiçaria o limite do plano.
      max: NA_VERCEL ? 1 : 5,
      idleTimeoutMillis: 10_000,
      connectionTimeoutMillis: 15_000,
    });
    pool.on("error", (erro) => console.error("Erro ocioso no pool do banco:", erro));
  }
  return pool;
}

export interface Resultado {
  rows: Array<Record<string, any>>;
  rowCount: number;
}

export type Consulta = (sql: string, args?: unknown[]) => Promise<Resultado>;

/**
 * As consultas do projeto são escritas com "?" (mais legível ao montar filtros
 * dinâmicos); o PostgreSQL usa $1, $2... A conversão acontece aqui.
 */
function comPlaceholders(sql: string): string {
  let indice = 0;
  return sql.replace(/\?/g, () => `$${(indice += 1)}`);
}

export async function consultar(sql: string, args: unknown[] = []): Promise<Resultado> {
  const resultado = await conexoes().query(comPlaceholders(sql), args);
  return { rows: resultado.rows, rowCount: resultado.rowCount ?? 0 };
}

/** Executa várias consultas numa transação, desfazendo tudo em caso de erro. */
export async function transacao<T>(acao: (q: Consulta) => Promise<T>): Promise<T> {
  const cliente = await conexoes().connect();
  const consulta: Consulta = async (sql, args = []) => {
    const resultado = await cliente.query(comPlaceholders(sql), args);
    return { rows: resultado.rows, rowCount: resultado.rowCount ?? 0 };
  };
  try {
    await cliente.query("BEGIN");
    const valor = await acao(consulta);
    await cliente.query("COMMIT");
    return valor;
  } catch (erro) {
    await cliente.query("ROLLBACK").catch(() => {});
    throw erro;
  } finally {
    cliente.release();
  }
}

/** Código do PostgreSQL para violação de restrição de unicidade. */
export const UNICIDADE_VIOLADA = "23505";

/** Usado nos testes, para trocar de banco entre um caso e outro. */
export async function resetarConexao(): Promise<void> {
  const anterior = pool;
  pool = undefined;
  schemaPronto = undefined;
  await anterior?.end().catch(() => {});
}

const SCHEMA = [
  `CREATE TABLE IF NOT EXISTS pastas (
      id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome      TEXT    NOT NULL UNIQUE,
      subtitulo TEXT    NOT NULL DEFAULT '',
      icone     TEXT    NOT NULL DEFAULT 'folder',
      cor       TEXT    NOT NULL DEFAULT '#3b82f6',
      ordem     INTEGER NOT NULL DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS contas (
      id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      pasta_id INTEGER REFERENCES pastas(id) ON DELETE CASCADE,
      codigo   TEXT    NOT NULL DEFAULT '',
      nome     TEXT    NOT NULL,
      tipo     TEXT    NOT NULL CHECK (tipo IN ('receita', 'despesa')),
      cor      TEXT    NOT NULL DEFAULT '#3b82f6',
      ativo    INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_contas_unicas
      ON contas ((COALESCE(pasta_id, -1)), tipo, nome)`,
  `CREATE TABLE IF NOT EXISTS lancamentos (
      id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      pasta_id       INTEGER NOT NULL REFERENCES pastas(id) ON DELETE CASCADE,
      conta_id       INTEGER NOT NULL REFERENCES contas(id) ON DELETE RESTRICT,
      tipo           TEXT    NOT NULL CHECK (tipo IN ('receita', 'despesa')),
      data           TEXT    NOT NULL,
      descricao      TEXT    NOT NULL DEFAULT '',
      valor_centavos BIGINT  NOT NULL CHECK (valor_centavos > 0),
      observacao     TEXT    NOT NULL DEFAULT '',
      criado_em      TIMESTAMPTZ NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS idx_lanc_data  ON lancamentos (data)`,
  `CREATE INDEX IF NOT EXISTS idx_lanc_pasta ON lancamentos (pasta_id, data)`,
  `CREATE INDEX IF NOT EXISTS idx_lanc_conta ON lancamentos (conta_id)`,
];

/** Pastas iniciais: os três centros de custo. */
const PASTAS_PADRAO: Array<[string, string, string, string, number]> = [
  ["Corretor", "Comissões • Despesas • Lucro", "corretor", "#f5a524", 1],
  ["Barbearia", "Vendas • Despesas • Lucro", "barbearia", "#3b82f6", 2],
  ["Casa", "Moradia • Contas • Despesas", "casa", "#22c55e", 3],
];

/** Plano de contas inicial: [pasta, código, nome, tipo, cor]. */
const CONTAS_PADRAO: Array<[string, string, string, "receita" | "despesa", string]> = [
  ["Corretor", "1.01", "Comissão de venda", "receita", "#22c55e"],
  ["Corretor", "1.02", "Comissão de locação", "receita", "#16a34a"],
  ["Corretor", "1.99", "Outras receitas", "receita", "#4ade80"],
  ["Corretor", "2.01", "Combustível", "despesa", "#3b82f6"],
  ["Corretor", "2.02", "Marketing", "despesa", "#f97316"],
  ["Corretor", "2.03", "Alimentação", "despesa", "#22c55e"],
  ["Corretor", "2.04", "Internet/Telefone", "despesa", "#8b5cf6"],
  ["Corretor", "2.99", "Outros", "despesa", "#94a3b8"],
  ["Barbearia", "1.01", "Serviços (cortes e barba)", "receita", "#22c55e"],
  ["Barbearia", "1.02", "Venda de produtos", "receita", "#16a34a"],
  ["Barbearia", "1.99", "Outras receitas", "receita", "#4ade80"],
  ["Barbearia", "2.01", "Produtos (pomadas, etc.)", "despesa", "#3b82f6"],
  ["Barbearia", "2.02", "Aluguel", "despesa", "#f97316"],
  ["Barbearia", "2.03", "Energia/Água", "despesa", "#22c55e"],
  ["Barbearia", "2.04", "Internet/Telefone", "despesa", "#8b5cf6"],
  ["Barbearia", "2.99", "Outros", "despesa", "#94a3b8"],
  ["Casa", "1.01", "Salário", "receita", "#22c55e"],
  ["Casa", "1.02", "Bônus/Extras", "receita", "#16a34a"],
  ["Casa", "1.99", "Outras receitas", "receita", "#4ade80"],
  ["Casa", "2.01", "Moradia (aluguel/cond.)", "despesa", "#3b82f6"],
  ["Casa", "2.02", "Contas (água, luz, internet)", "despesa", "#f97316"],
  ["Casa", "2.03", "Alimentação", "despesa", "#22c55e"],
  ["Casa", "2.04", "Transporte", "despesa", "#8b5cf6"],
  ["Casa", "2.99", "Outros", "despesa", "#ec4899"],
];

let schemaPronto: Promise<void> | undefined;

/**
 * Cria as tabelas e, se o banco estiver vazio, os dados iniciais.
 * Roda uma única vez por instância — as chamadas seguintes reaproveitam a promessa.
 */
export function prepararBanco(): Promise<void> {
  if (!schemaPronto) {
    schemaPronto = (async () => {
      for (const comando of SCHEMA) await consultar(comando);

      const { rows } = await consultar("SELECT COUNT(*) AS n FROM pastas");
      if (Number(rows[0]?.n ?? 0) > 0) return;

      await transacao(async (q) => {
        const ids = new Map<string, number>();
        for (const [nome, subtitulo, icone, cor, ordem] of PASTAS_PADRAO) {
          const criada = await q(
            "INSERT INTO pastas (nome, subtitulo, icone, cor, ordem) VALUES (?, ?, ?, ?, ?) RETURNING id",
            [nome, subtitulo, icone, cor, ordem],
          );
          ids.set(nome, Number(criada.rows[0]?.id));
        }
        for (const [pasta, codigo, nome, tipo, cor] of CONTAS_PADRAO) {
          await q(
            "INSERT INTO contas (pasta_id, codigo, nome, tipo, cor) VALUES (?, ?, ?, ?, ?)",
            [ids.get(pasta) ?? null, codigo, nome, tipo, cor],
          );
        }
      });
    })().catch((erro) => {
      schemaPronto = undefined; // permite tentar de novo na próxima requisição
      throw erro;
    });
  }
  return schemaPronto;
}
